"""boxmunge bundle <project-dir> — build a validated, ready-to-upload bundle."""
from __future__ import annotations
import sys
import tarfile
from datetime import datetime, timezone
from pathlib import Path
import yaml
from boxmunge_cli.manifest import load_manifest, validate_manifest, ManifestError
from boxmunge_cli.ulid import generate_ulid


BUNDLE_HELP = """\
boxmunge bundle — build a validated, ready-to-upload project bundle

Usage:
  boxmunge bundle <project-dir> [--output PATH] [--validate]

Options:
  --output PATH    Write bundle to this directory (default: parent of project dir)
  --validate       Validate only, don't create the bundle

The project directory must contain:

  manifest.yml     Project manifest (see below)
  compose.yml      Docker Compose file for the project's services

A ULID (unique project ID) is generated and written into manifest.yml
automatically if not already present.

Manifest format (manifest.yml):

  id: <auto-generated ULID>
  project: myapp                    # must match the directory name
  source: bundle                    # 'bundle' or 'git'
  hosts:
    - myapp.example.com             # hostnames Caddy will serve
  services:
    frontend:
      port: 3000                    # container port
      routes:
        - path: /                   # URL path to route to this service
      smoke: boxmunge-scripts/smoke.sh  # smoke test script (runs in container)
      limits:                       # optional resource constraints
        memory: 512m
        cpus: "0.5"
    backend:
      port: 8000
      routes:
        - path: /api/*
      limits:
        memory: 1g
        cpus: "1.0"
  backup:
    type: none                      # none | volume | db-dump | both

After building:

  scp -P 922 <bundle>.tar.gz deploy@<host>:
  ssh -p 922 deploy@<host> "stage <project>"
  ssh -p 922 deploy@<host> "promote <project>"

Or skip staging:

  ssh -p 922 deploy@<host> "deploy <project>"
"""

def run_bundle(project_dir_str: str, output: str | None = None,
               validate_only: bool = False) -> int:
    project_dir = Path(project_dir_str).resolve()
    if not project_dir.is_dir():
        print(f"ERROR: Not a directory: {project_dir}")
        return 1

    manifest_path = project_dir / "manifest.yml"
    if not manifest_path.exists():
        print(f"ERROR: No manifest.yml in {project_dir}")
        return 1

    try:
        manifest = load_manifest(manifest_path)
    except ManifestError as e:
        print(f"ERROR: {e}")
        return 1

    project_name = manifest.get("project", project_dir.name)

    if not manifest.get("id"):
        ulid = generate_ulid()
        # Insert id at the top of the manifest (convention: id is first field)
        manifest = {"id": ulid, **manifest}
        manifest_path.write_text(yaml.dump(manifest, default_flow_style=False, sort_keys=False))
        print(f"  Generated ULID: {ulid}")

    errors, warnings = validate_manifest(manifest, project_name)
    if errors:
        print("ERROR: Manifest validation failed:")
        for e in errors:
            print(f"  {e}")
        return 1
    for w in warnings:
        print(f"  WARN: {w}")

    compose_path = project_dir / "compose.yml"
    if not compose_path.exists():
        print(f"ERROR: No compose.yml in {project_dir}")
        return 1

    try:
        compose_data = yaml.safe_load(compose_path.read_text())
        if not isinstance(compose_data, dict):
            print("ERROR: compose.yml is not a valid YAML mapping")
            return 1
    except yaml.YAMLError as e:
        print(f"ERROR: compose.yml parse error: {e}")
        return 1

    if validate_only:
        print(f"Validation passed for '{project_name}'.")
        return 0

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%S")
    filename = f"{project_name}-{timestamp}.tar.gz"

    if output:
        output_path = Path(output).resolve()
        bundle_path = output_path / filename if output_path.is_dir() else output_path
    else:
        bundle_path = project_dir.parent / filename

    with tarfile.open(bundle_path, "w:gz") as tar:
        tar.add(project_dir, arcname=project_name)

    size_mb = bundle_path.stat().st_size / (1024 * 1024)
    print(f"Bundle created: {bundle_path}")
    print(f"  Size: {size_mb:.1f} MB")
    print(f"  Upload with: scp -P 922 {bundle_path.name} deploy@<host>:")
    return 0

def cmd_bundle(args: list[str]) -> None:
    validate_only = "--validate" in args
    output = None
    positional = []
    filtered = [a for a in args if a != "--validate"]
    i = 0
    while i < len(filtered):
        if filtered[i] == "--output" and i + 1 < len(filtered):
            output = filtered[i + 1]
            i += 2
        elif not filtered[i].startswith("--"):
            positional.append(filtered[i])
            i += 1
        else:
            i += 1
    if not positional:
        print(BUNDLE_HELP)
        sys.exit(2)
    sys.exit(run_bundle(positional[0], output=output, validate_only=validate_only))
